### ISSUE TITLE
Save As option  not working on 3.36

### ISSUE THREAD

**Issue by terencode** [OttoAllmendinger/gnome-shell-screenshot#129]
Here is what I see in the log when I try to use the "Save As..." option: 
```
juin 23 19:51:45 terence-desktop gjs[256371]: JS WARNING: [/usr/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/saveDlg.js 24]: Too many arguments to function Gtk.init: expected 0, got 2
juin 23 19:51:45 terence-desktop gjs[256371]: JS WARNING: [/usr/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/saveDlg.js 11]: Requiring Gtk but it has 3 versions available; use imports.gi.versions to pick one
```

```
Script /usr/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/saveDlg.js threw an exception juin 23 19:51:45 terence-desktop gjs[256371]: JS ERROR: TypeError: dlg.set_do_overwrite_confirmation is not a function copy@/usr/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/saveDlg.js:31:7 @/usr/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/saveDlg.js:57:3 juin 23 19:51:45 terence-desktop gjs[256371]: JS WARNING: [/usr/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/saveDlg.js 24]: Too many arguments to function Gtk.init: expected 0, got 2 juin 23 19:51:45 terence-desktop gjs[256371]: JS WARNING: [/usr/share/gnome-shell/extensions/gnome-shell-screenshot@ttll.de/saveDlg.js 11]: Requiring Gtk but it has 3 versions available; use imports.gi.versions to pick one
```

My setup:
- Gnome-shell 3.36.3
- ArchLinux with linux 5.7.5
- gjs 1.65.3

**Comment by matthijskooijman** [comment]
I'm seeing just one of those errors, with different numbers:

```
ome-shell/extensions/gnome-shell-screenshot@ttll.de/saveDlg.js 24]: Too many arguments to function Gtk.init: expected 1, got 2
```

For me, the save dialog *does* appear and I can save the screenshot properly (by clicking the extension icon and then selecting "Save as...").

 - Gnome-shell 3.36.4
 - Ubuntu Focal
 - gjs 1.64.3

**Comment by OttoAllmendinger** [comment]
this should be fixed in https://github.com/OttoAllmendinger/gnome-shell-screenshot/tree/v50 (pending review on extensions.gnome.org)
