### ISSUE TITLE
Doesnt work in GNOME 3.32 

### ISSUE THREAD

**Issue by thankjura** [OttoAllmendinger/gnome-shell-screenshot#87]
Extension "gnome-shell-screenshot@ttll.de" had error: TypeError: this._construct is not a function

**Comment by thankjura** [comment]
https://github.com/micheleg/dash-to-dock/issues/877

**Comment by vageliskatsiotis** [comment]
Hi. This build brings back dash-to-dock but still gnome-shell-screenshot throws error.
[https://aur.archlinux.org/packages/gnome-shell-extension-dash-to-dock-git](url).

Any way to provide shell error output for this bug?

**Comment by corebots** [comment]
oh yes, please update for 3.32

**Comment by drakkar1969** [comment]
Thanks for the update for GNOME 3.32, now working again for me

**Comment by KSXGitHub** [comment]
I think issue can be closed now.

**Comment by OttoAllmendinger** [comment]
Fixed in https://github.com/OttoAllmendinger/gnome-shell-screenshot/commit/71b69c75241211d8613889db8cc9c09ce1b2bb8d
